//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazLab2_Proje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Logs
    {
        public int LogID { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public string LogDetails { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    
        public virtual Tbl_Articles Tbl_Articles { get; set; }
    }
}
