//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazLab2_Proje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Articles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Articles()
        {
            this.Tbl_Logs = new HashSet<Tbl_Logs>();
            this.Tbl_Anonim = new HashSet<Tbl_Anonim>();
            this.Tbl_Messages = new HashSet<Tbl_Messages>();
        }
    
        public int ArticleID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Title { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.Guid> TrackingNumber { get; set; }
        public Nullable<bool> Anonim { get; set; }
    
        public virtual Tbl_Users Tbl_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Logs> Tbl_Logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Anonim> Tbl_Anonim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Messages> Tbl_Messages { get; set; }
    }
}
