//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazLab2_Proje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Anonim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Anonim()
        {
            this.Tbl_ArticleHakem = new HashSet<Tbl_ArticleHakem>();
        }
    
        public int AnonimID { get; set; }
        public Nullable<int> OrijinalArticleID { get; set; }
        public string AnonimFields { get; set; }
        public string AnonimFilePath { get; set; }
        public string AnonimTitle { get; set; }
        public Nullable<System.DateTime> AnonimDate { get; set; }
        public string AnonimStatus { get; set; }
    
        public virtual Tbl_Articles Tbl_Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ArticleHakem> Tbl_ArticleHakem { get; set; }
    }
}
